export const userConstants = {
  	USER_CREATE_REQUEST: 'USERS_SUBMIT_REQUEST',
    USER_CREATE_SUCCESS: 'USERS_SUBMIT_SUCCESS',
    USER_CREATE_FAILURE: 'USERS_SUBMIT_FAILURE',
    USER_GET_REQUEST: 'USERS_FETCH_REQUEST',
    USER_GET_SUCCESS: 'USERS_FETCH_SUCCESS',
    USER_GET_FAILURE: 'USERS_FETCH_FAILURE'
}

export const transferConstants = {
  	TRANSFER_REQUEST: 'TRANSFER_METHOD_REQUEST',
    TRANSFER_SUCCESS: 'TRANSFER_METHOD_SUCCESS',
   	TRANSFER_FAILURE: 'TRANSFER_METHOD_FAILURE'
}

export const paymentConstants = {
  	PAYMENT_REQUEST: 'PAYMENT_SUBMIT_REQUEST',
    PAYMENT_SUCCESS: 'PAYMENT_SUBMIT_SUCCESS',
   	PAYMENT_FAILURE: 'PAYMENT_SUBMIT_FAILURE'
}